# Generated by Django 3.1.2 on 2020-11-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0011_auto_20201022_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleParagraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_article', models.IntegerField()),
                ('paragraph_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='paragraph_default.jpg', upload_to='paragraph_pic')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articleparagraphs')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_paragraph', models.TextField()),
                ('ending_paragaph', models.TextField()),
                ('article_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.AddField(
            model_name='articleparagraphs',
            name='parent_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.completearticle'),
        ),
    ]
