# Generated by Django 3.1.2 on 2020-11-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201022_1713'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=70)),
                ('lead_paragraph', models.TextField()),
                ('ending_paragaph', models.TextField()),
                ('article_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.RenameModel(
            old_name='ParagraphImages',
            new_name='ParagraphImage',
        ),
        migrations.RenameModel(
            old_name='ArticleParagraphs',
            new_name='ArticleParagraph',
        ),
        migrations.DeleteModel(
            name='CompleteArticle',
        ),
        migrations.AlterField(
            model_name='articleparagraph',
            name='parent_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.fullarticle'),
        ),
    ]
