# Generated by Django 3.1.2 on 2020-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20201111_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='article_default.jpg', upload_to='article_main_image')),
                ('brief_summary', models.TextField()),
                ('section', models.CharField(max_length=80)),
                ('date', models.DateField()),
            ],
        ),
    ]
