# Generated by Django 3.1.2 on 2020-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(default='This is an image', max_length=70),
        ),
    ]
