# Generated by Django 3.1.2 on 2020-11-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='pub_date',
        ),
    ]
