# Generated by Django 3.1.2 on 2020-11-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20201126_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullarticle',
            old_name='article_brief',
            new_name='belongs_to',
        ),
    ]
