# Generated by Django 3.1.2 on 2020-11-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20201126_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullarticle',
            old_name='belongs_to',
            new_name='short_article',
        ),
    ]
