# Generated by Django 3.1.2 on 2020-10-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='article_pics')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.article_presentation')),
            ],
        ),
    ]
