# Generated by Django 3.1.2 on 2020-10-21 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article_presentation',
            new_name='article',
        ),
    ]
