# Generated by Django 3.1.2 on 2020-10-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_info',
            old_name='owner',
            new_name='user',
        ),
    ]
