# Generated by Django 3.1.2 on 2020-10-22 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20201022_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_introduction_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('image', models.ImageField(default='default_user_pic.jpg', upload_to='user_pics')),
                ('slogan', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
