# Generated by Django 3.1.2 on 2020-10-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_user_introduction_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_image',
            name='user',
        ),
        migrations.DeleteModel(
            name='contact_info',
        ),
        migrations.DeleteModel(
            name='user_image',
        ),
    ]
