# Generated by Django 3.1.2 on 2020-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_homepageprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHeaderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=80)),
            ],
        ),
    ]
