# Generated by Django 3.1.2 on 2020-11-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201120_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionHeaderData',
            new_name='SectionHeader',
        ),
    ]
