# Generated by Django 3.1.2 on 2020-11-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201120_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_introduction_data',
        ),
    ]
