# Generated by Django 3.1.2 on 2020-12-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_user_introduction_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_image',
            name='article',
        ),
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='article_image',
        ),
    ]
